---
title: "fdi_paper"
author: "Daniel Shapiro"
date: "4/16/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
options(scipen = 999)
library(tidyverse)
library(readxl)
library(readr)
library(gsubfn)
library(zoo)
library(ggpubr)
```
# Figure 1

```{r oecddat}
quartinv <- read_csv("raw-data/DP_LIVE_22042020222930826.csv", col_types = cols(
  LOCATION = col_character(),
  INDICATOR = col_character(),
  SUBJECT = col_character(),
  MEASURE = col_character(),
  FREQUENCY = col_character(),
  TIME = col_character(),
  Value = col_double(),
  `Flag Codes` = col_logical()
))

# Read in CSV

quartinv$TIME <- gsubfn("Q.*", list(`Q1` = 1, `Q2` = 2, `Q3` = 3, `Q4` = 4), quartinv$TIME)
quartinv$TIME <- as.yearqtr(quartinv$TIME)

ggplot(quartinv, aes(x = TIME, y = Value)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(y = "FDI Inflow, Millions USD",
       x = "Quarter",
       title = "Russian Quarterly FDI Inflow in Millions USD",
       subtitle = "Data from OECD",
       caption = "OECD data can be found at https://data.oecd.org/fdi/fdi-flows.htm. OECD measures quarterly data for Russia from 2013.")

ggsave(filename = "fdi.png")
```

# Figure 2

```{r fig2}
bricsfdi <- read_csv("raw-data/DP_LIVE_22042020233939640.csv", col_types = cols(
  LOCATION = col_character(),
  INDICATOR = col_character(),
  SUBJECT = col_character(),
  MEASURE = col_character(),
  FREQUENCY = col_character(),
  TIME = col_double(),
  Value = col_double(),
  `Flag Codes` = col_logical()
)) %>%
  group_by(LOCATION) %>%
  mutate(Country = LOCATION) %>%
  select(-LOCATION)

bricsfdi$Country <- recode(bricsfdi$Country, 
                           "ZAF" = "South Africa",
                           "BRA" = "Brazil",
                           "CHN" = "China",
                           "IND" = "India",
                           "RUS" = "Russia")

ggplot(bricsfdi, aes(x = TIME, y = Value, color = Country)) +
  geom_line() +
  geom_point() +
  labs(y = "FDI Inflow, Millions USD",
       x = "Year",
       title = "BRICS Countries' Yearly FDI Inflow in Millions USD",
       subtitle = "Data from OECD",
       caption = "OECD data can be found at https://data.oecd.org/fdi/fdi-flows.htm. Yearly data measured from 2005.")

ggsave(filename = "bricsfdi.png")
```

# FDI Stock

```{r fdistoc}
stock <- read_csv("raw-data/DP_LIVE_23042020171303158.csv", col_types = cols(
  LOCATION = col_character(),
  INDICATOR = col_character(),
  SUBJECT = col_character(),
  MEASURE = col_character(),
  FREQUENCY = col_character(),
  TIME = col_double(),
  Value = col_double(),
  `Flag Codes` = col_logical()
))

ggplot(stock, aes(x = TIME, y = Value)) +
  geom_point() +
  geom_line() +
  labs(y = "FDI Stock (Inward), Millions USD",
       x = "Year",
       title = "Russian Yearly FDI Stock in Millions USD",
       subtitle = "Data from OECD",
       caption = "OECD data can be found at https://data.oecd.org/fdi/fdi-stocks.htm. Yearly data measured from 2005.")

ggsave(filename = "rufdistock.png")
```

# FDI Stock Comparative w/Brazil, SA

```{r compare}
stockcomp <- read_csv("raw-data/DP_LIVE_23042020173537182.csv", col_types = cols(
  LOCATION = col_character(),
  INDICATOR = col_character(),
  SUBJECT = col_character(),
  MEASURE = col_character(),
  FREQUENCY = col_character(),
  TIME = col_double(),
  Value = col_double(),
  `Flag Codes` = col_logical()
)) %>%
  group_by(LOCATION) %>%
  mutate(Country = LOCATION) %>%
  select(-LOCATION)

stockcomp$Country <- recode(stockcomp$Country, 
                           "ZAF" = "South Africa",
                           "BRA" = "Brazil",
                           "CHN" = "China",
                           "IND" = "India",
                           "RUS" = "Russia")

stock1 <- ggplot(stockcomp, aes(x = TIME, y = Value, color = Country)) +
  geom_line() +
  geom_point() +
  labs(y = "FDI Stock, Millions USD",
       x = "Year",
       title = "Russia, S. Africa, Brazil Yearly FDI Stock in Millions USD",
       subtitle = "Data from OECD",
       caption = "OECD data can be found at https://data.oecd.org/fdi/fdi-stocks.htm. Yearly data measured from 2005.")

ggsave(stock1, filename = "compstock.png", width = 7.29, height = 4.5)

gdppct <- read_csv("raw-data/DP_LIVE_23042020175352091.csv") %>%
  group_by(LOCATION) %>%
  mutate(Country = LOCATION) %>%
  select(-LOCATION)

gdppct$Country <- recode(gdppct$Country, 
                           "ZAF" = "South Africa",
                           "BRA" = "Brazil",
                           "CHN" = "China",
                           "IND" = "India",
                           "RUS" = "Russia")

stock2 <- ggplot(gdppct, aes(x = TIME, y = Value, color = Country)) +
  geom_line() +
  geom_point() +
  labs(y = "FDI Stock as % GDP",
       x = "Year",
       title = "BRICS Countries' Yearly FDI Stock As Percent of GDP",
       subtitle = "Data from OECD")

ggsave(stock2, filename = "stockcomp.png", width = 7.29, height = 4.5)
```

# Greenfield

```{r greenfield}
greenf <- read_xlsx("raw-data/greenfield.xlsx")

rusdat <- greenf %>%
  pivot_longer(-`Destination region/economy`, names_to = "Year", values_to = "Amount") %>%
  filter(`Destination region/economy` == "Russian Federation")

ggplot(rusdat, aes(x = as.numeric(Year), y = Amount)) +
  geom_point() +
  geom_line() +
  labs(x = "Year",
       y = "Value, Millions USD",
       title = "Value of Announced Greenfield FDI Projects in Russia",
       subtitle = "Data from UNCTAD",
       caption = "UN data can be found at: https://unctad.org/en/Pages/DIAE/World%20Investment%20Report/Annex-Tables.aspx")
```

# P/E
```{r readin, message = FALSE, warning = FALSE}
south_africa <- read_excel("raw-data/SAPE.xlsx") %>%
  select(`P/E`) %>%
  mutate(pe = as.numeric(`P/E`)) %>%
  head(100)

south_africa[is.na(south_africa)] <- 0

# Changed NAs to equal zero. Figures are listed as NAs in the original data when P/E ratio is negative. Since I'm only looking at medians, not means, I figure that putting them at zero will not affect scores too much.

brazil <- read_excel("raw-data/BPE.xlsx") %>%
  select(`P/E`) %>%
  mutate(pe = as.numeric(`P/E`)) %>%
  head(100)

brazil[is.na(brazil)] <- 0

russia <- read_excel("raw-data/RUSSPE.xlsx") %>%
  select(`P/E`) %>%
  mutate(pe = as.numeric(`P/E`)) %>%
  head(100)

russia[is.na(russia)] <- 0

china <- read_excel("raw-data/CPE.xlsx") %>%
  select(`P/E`) %>%
  mutate(pe = as.numeric(`P/E`)) %>%
  head(100)

china[is.na(china)] <- 0

india <- read_excel("raw-data/IPE.xlsx") %>%
  select(`P/E`) %>%
  mutate(pe = as.numeric(`P/E`)) %>%
  head(100)

india[is.na(india)] <- 0
```

```{r messingaround}
# Just want to see distributions so I know what I'm working with. Not crucial. 

ggplot(south_africa, aes(x = pe)) +
  geom_histogram() +
   scale_x_log10()

ggplot(brazil, aes(x = pe)) +
  geom_histogram()+
   scale_x_log10()

ggplot(india, aes(x = pe)) +
  geom_histogram()+
   scale_x_log10()

ggplot(russia, aes(x = pe)) +
  geom_histogram()+
   scale_x_log10()

ggplot(china, aes(x = pe)) +
  geom_histogram() +
  scale_x_log10()
```

```{r}
# Summarize medians. Medians mitigate extreme outliers and show general trends better than means.

brazil %>%
  summarize(bmed = median(pe))

south_africa %>%
  summarize(smed = median(pe))

russia %>%
  summarize(rmed = median(pe))

china %>%
  summarize(cmed = median(pe))

india %>%
  summarize(imed = median(pe))
```

